#!/bin/bash
# Script to install Docker container for nanomachine

# Run precheck, if fails stop
SCRIPT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
$SCRIPT_DIR/precheck || exit 1

BRIDGE_DIR=$SCRIPT_DIR/../../bridge

CONTAINER_NAME="nanomachine-vm"
CONTAINER_USER="abc"
CONTAINER_HOME="/home/abc"
HOST_VNC_PORT="3201"
HOST_BRIDGE_PORT="8787"

# Check if container exists, if it does exist exit
if [ -n "$(docker ps -a -q -f name=$CONTAINER_NAME)" ]; then
  echo "VM already installed"
  exit 1
fi

# Start the container
docker run -d \
  --name=$CONTAINER_NAME \
  --security-opt seccomp=unconfined `#optional` \
  -e PUID=1000 \
  -e PGID=1000 \
  -e TZ=Etc/UTC \
  -p $HOST_VNC_PORT:3000 \
  -p $HOST_BRIDGE_PORT:8787 \
  -v $SCRIPT_DIR/../../vm:/config \
  --shm-size="1gb" \
  --restart unless-stopped \
  linuxserver/chromium:version-cc16b1d1

# Wait for container to initialize
$SCRIPT_DIR/wait || exit 1

#################################
# ===== BRIDGE INSTALLATION =====
#################################

$SCRIPT_DIR/install-bridge || exit 1

# ===== END OF BRIDGE INSTALLATION =====

######################################
# ===== NANOBROWSER INSTALLATION =====
######################################

$SCRIPT_DIR/install-nanobrowser || exit 1

# ===== END OF NANOBROWSER INSTALLATION =====


echo "VM installed successfully"
exit 0
