#!/bin/bash
# Script to stop Docker container for nanomachine

# Run precheck, if fails stop
SCRIPT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
$SCRIPT_DIR/precheck || exit 1

CONTAINER_NAME="nanomachine-vm"

$SCRIPT_DIR/stop || true
$SCRIPT_DIR/start || exit 1

exit 0
