#!/bin/bash
# Script to start Docker container for nanomachine

# Run precheck, if fails stop
SCRIPT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
$SCRIPT_DIR/precheck || exit 1

CONTAINER_NAME="nanomachine-vm"

# Check if container exists
if [ -z "$(docker ps -a -q -f name=$CONTAINER_NAME)" ]; then
  $SCRIPT_DIR/install || exit 1
  BYPASS_RUN_CHECK=true
fi

# Check if container is running
if [ -z "$BYPASS_RUN_CHECK" ] && [ -n "$(docker ps -q -f name=$CONTAINER_NAME)" ]; then
  echo "VM already running"
  exit 0
fi

docker start $CONTAINER_NAME

$SCRIPT_DIR/wait || exit 1
$SCRIPT_DIR/run || exit 1

echo "VM started"
exit 0